version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes", "--save", "60", "100"]
    networks:
      - soat-network

  kitchen-service:
    build: .
    image: soat4/kitchen-service
    container_name: kitchen-service
    command: bundle exec puma -C config/puma.rb
    environment:
      REDIS_URL: redis://redis:6379/1
      PORT: 3002
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - redis
    ports:
      - "3002:3002"
    networks:
      - soat-network

  sidekiq:
    image: soat4/kitchen-service
    command: bundle exec sidekiq -C config/sidekiq.yml
    environment:
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - redis
    networks:
      - soat-network

  kitchen-consumer:
    image: soat4/kitchen-service
    container_name: kitchen-consumer
    command: bundle exec rails runner "StartKitchenConsumer.run"
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - kitchen-service
    networks:
      - soat-network
    restart: always

volumes:
  redis_data:

networks:
  soat-network:
    external: true
