apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitchen-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kitchen-api
  template:
    metadata:
      labels:
        app: kitchen-api
    spec:
      containers:
      - name: kitchen-service
        image: soat4/kitchen-service:latest
        command: ["bundle", "exec", "puma", "-C", "config/puma.rb"] #
        ports:
        - containerPort: 3002
        envFrom:
        - configMapRef:
            name: kitchen-service-config
        - secretRef:
            name: kitchen-service-secrets
        readinessProbe:
          httpGet:
            path: /up
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 10
