apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitchen-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kitchen-consumer 
  template:
    metadata:
      labels:
        app: kitchen-consumer 
    spec:
      containers:
        - name: consumer
          image: soat4/kitchen-service:latest
          command: ["bundle", "exec", "rails", "runner", "StartKitchenConsumer.run"]
          envFrom:
          - configMapRef:
              name: kitchen-service-config
          - secretRef:
              name: kitchen-service-secrets