apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kitchen-ingress
spec:
  rules:
  - http:
      paths:
      - path: /api/v1/production
        pathType: Prefix
        backend:
          service:
            name: kitchen-api-service
            port:
              number: 80